# For more information: https://laravel.com/docs/sail
version: '3'
services:
    baragenda.test:
        container_name: baragenda.test
        build:
            context: ./vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-1000}'
                WWWUSER: '${WWWUSER:-1000}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '1000'
            WWWGROUP: '1000'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - baragenda.mariadb
    baragenda.mariadb:
        container_name: baragenda.mariadb
        image: 'mariadb:10'
        hostname: db
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mariadb:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    #phpmyadmin
    baragenda.phpmyadmin:
        container_name: baragenda.phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: '${DB_PASSWORD}'
        ports:
            - '${FORWARD_PMA_PORT:-8088}:80'
        networks:
            - sail
volumes:
    sail-mariadb:
        driver: local
networks:
  sail:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.23.0.1/24
    driver_opts:
     com.docker.network.bridge.name: baragenda_net
